import { Public_Sans } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/provider/ContextProvider";

const public_Sans = Public_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={public_Sans.className}>
        <ContextProvider>
          {children}
        </ContextProvider>
        </body>
    </html>
  );
}
